In [2]:
import numpy as np
#import matplotlib.pyplot as plt
# lacuong@it.tdt.edu.vn 

In [3]:
X = np.array([[1,   2,   3,   4,   5,   6,   7],
              [1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5]])  #X la` ma?ng 2 chie^`u, chie^`u thu 1 co length = 2, co`n lai = 7.
y = np.array([[2,   4,   6,   8,   10,  12,  14]])   #y la` ma?ng 2 chie^`u, (1x7).
print(X.shape)
one = np.ones((X.shape[1], 1)) #Tao ma?ng-so-1, voi shape la (X.shape[1], 1). Tuc la` ma?ng-so-1, 2 chie^`u, (7x1).
print('one:\n', one)
# X = np.array(X).T
X = X.T #Chuyen vi cua X, X tro thanh mang 2 (7x2).
print('X:\n', X)
X = np.concatenate((one, X), axis=1) #Ghep mảng X vào one theo cột-column (axis=1). X tro thanh ma?ng 2 chieu, (7x3).
# f(x) = w1.x1 + w2.x2 + ... + w7.x7 + w0.1          Do co them so bias la w0, nen them 1 vao X.
y = np.array(y).T              # y tro thanh ma?ng (7x1)
print('X new:\n', X)

(2, 7)
one:
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
X:
 [[1.  1.5]
 [2.  2.5]
 [3.  3.5]
 [4.  4.5]
 [5.  5.5]
 [6.  6.5]
 [7.  7.5]]
X new:
 [[1.  1.  1.5]
 [1.  2.  2.5]
 [1.  3.  3.5]
 [1.  4.  4.5]
 [1.  5.  5.5]
 [1.  6.  6.5]
 [1.  7.  7.5]]


In [4]:
# step 1: initialize and forward propagate  
# y = w_1 * x + w_0
def f(X, W):
    return np.dot(X,W)
# f(x) = w1x1 + w2x2 + ... + w7x7 + w0
# Dat w = [w0, w1, .. , w7].T; X = [1, x1, .. , x7]     Do co them so bias w0 => X them 1.
# f(x) = wX  = y_hat    voi y_hat la gia tri du doan, se tim sai so voi y.     w vector cot, X vector ha`ng.

In [5]:
# step 2: loss function
# Ham ma^'t ma't la tim sai so giua y va y_hat, y_hat = f(X, W).
# X va y khong doi => Ca^`n ti`m W de ha`m loss to^'u uu, ma` de ti`m toi uu,
#                                                                cach pho bien la giai bai toan dao ham (gradient) bang 0.
# loss = 1/2N . sigma(y_hat - y)^2, y_hat = f(X, W).

def loss(X, Y):
    sum = 0
    for i in range(len(X)):
        sum += (f(X[i], W) - Y[i])**2       # Dung binh phuong vi luon co dao ham, co`n tri tuyet doi tai 0 la khong xac dinh.
#     return sum/len(X)                     # Theo slide, em thay ham Loss = 1/2*N....
    return sum / 2*len(X)

In [6]:
# step 3: Differentiation
def derivate(X, Y, W):
    d=[]
    for k in range(X.shape[1]):
        sum = 0
        for i in range(X.shape[0]):
            sum += (f(X[i], W) - Y[i]) * X[i][k]
        d.append(sum / X.shape[0])
    return np.array(d)

In [7]:
#test
W = np.array([[1, 3.5, 5]]).T
d = derivate(X, y, W)
print(d)
d = 0.1*d
print(d)
W=W-d
print(W)

[[ 29.5 ]
 [144.  ]
 [158.75]]
[[ 2.95 ]
 [14.4  ]
 [15.875]]
[[ -1.95 ]
 [-10.9  ]
 [-10.875]]


In [8]:
# step 4: update weight 
epoch = 50
learning_rate = 0.01
epsilon = 0.01
W = np.array([[0,0,0]]).T
for iter in range(epoch):
    before_loss = loss(X,y)
    print(iter,': ',before_loss) 
    d = derivate(X,y,W)
    W = W - learning_rate*d
    if before_loss-loss(X,y) < epsilon:
        break 
# print result 
print('W:')
print(W)
# Sau moi epoch, loss giam dan cho toi lan thu 12.
# f(x) = 0.16424169x_1 + 0.89228794x_2 + 0.97440878x_3

0 :  [1960.]
1 :  [593.341]
2 :  [180.67524173]
3 :  [56.06566793]
4 :  [18.43404938]
5 :  [7.0652571]
6 :  [3.62649141]
7 :  [2.58220368]
8 :  [2.2609471]
9 :  [2.15803187]
10 :  [2.12106794]
11 :  [2.10404136]
12 :  [2.09305823]
W:
[[0.16424169]
 [0.89228794]
 [0.97440878]]
