In [11]:
# f = open('iris.data', 'r', encoding = 'utf-8')
# listIris = list()
# for line in f:
#     if line != '\n':
#         listIris.append(line)
# print(listIris[0])

In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv("Data/iris.data")
print(df.shape)
df.head(5)

(149, 5)


5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [2]:
data = df.values
print(data.shape)
print(data[:5])

(149, 5)
[[4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']]


In [3]:
#prepare data
X = data[:,:-1]
print('X = \n', X[:3])
y = data[:,-1:]
print('y = \n', y[:3])
y = y.ravel()#flat chuyển sang một chiều
print('y = \n', y[:3])

X = 
 [[4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
y = 
 [['Iris-setosa']
 ['Iris-setosa']
 ['Iris-setosa']]
y = 
 ['Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [4]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
y = LE.fit_transform(y)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 4)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(119, 4) (119,)
(30, 4) (30,)


In [6]:
print(X_train[:3])
print(y_train[:3])

[[6.3 2.8 5.1 1.5]
 [4.7 3.2 1.3 0.2]
 [6.1 3.0 4.6 1.4]]
[2 0 1]


In [15]:
#Phan loai voi KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k = 5
knn = KNeighborsClassifier(n_neighbors=k, metric='euclidean')
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
print('y_pred:\n', y_pred)
print('y_true:\n', y_test)

#Tính accuracy
acc_score = metrics.accuracy_score(y_pred, y_test)
print('accuracy:\n', acc_score)

print('confusion matrix step')
from sklearn.metrics import precision_recall_fscore_support as score

precision,recall,fscore,support = score(y_test, y_pred)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
print('fscore: {}'.format(fscore))
print('support: {}'.format(support))

print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))
print('Accuracy:', metrics.accuracy_score(y_test, y_pred))

y_pred:
 [0 0 0 2 0 0 2 0 1 0 2 0 0 1 2 0 0 1 0 1 1 0 2 0 2 0 0 1 0 2]
y_true:
 [0 0 0 2 0 0 1 0 1 0 2 0 0 1 2 0 0 1 0 1 1 0 2 0 2 0 0 2 0 2]
accuracy:
 0.9333333333333333
confusion matrix step
precision: [1.         0.83333333 0.85714286]
recall: [1.         0.83333333 0.85714286]
fscore: [1.         0.83333333 0.85714286]
support: [17  6  7]
[[17  0  0]
 [ 0  5  1]
 [ 0  1  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.83      0.83      0.83         6
           2       0.86      0.86      0.86         7

    accuracy                           0.93        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.93      0.93      0.93        30

Accuracy: 0.9333333333333333


In [ ]:
# print('Confusion matrix self step')
# true_pos = 0
# true_neg = 0
# false_pos = 0
# false_neg = 0
# for cur in range(len(y_pred)):
#     if y_pred[cur] == y_test[cur]: true_pos+=1
    
# print(true_pos)

In [8]:
#Ví dụ về SVM
from sklearn import svm
svm_classifier = svm.SVC(kernel='linear', gamma=0.01, C=100.)
svm_classifier.fit(X_train, y_train)

y_pred_svm = svm_classifier.predict(X_test)
print('y_pred_svm:\n', y_pred_svm)
print('y_true:\n', y_test)

acc_score_svm = metrics.accuracy_score(y_pred_svm, y_test)
print('accuracy:\n', acc_score_svm)

y_pred_svm:
 [0 0 0 2 0 0 2 0 1 0 2 0 0 1 2 0 0 1 0 1 1 0 2 0 2 0 0 2 0 2]
y_true:
 [0 0 0 2 0 0 1 0 1 0 2 0 0 1 2 0 0 1 0 1 1 0 2 0 2 0 0 2 0 2]
accuracy:
 0.9666666666666667


In [9]:
#Thử nghiệm với Logistic Regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model = model.fit(X_train, y_train)
y_pred_logistic = model.predict(X_test)
print('y_pred_logistic:\n', y_pred_logistic)
acc_score_logistic = metrics.accuracy_score(y_pred_logistic, y_test)
print('accuracy:\n', acc_score_logistic)

y_pred_logistic:
 [0 0 0 2 0 0 2 0 1 0 2 0 0 1 2 0 0 1 0 1 1 0 2 0 2 0 0 1 0 2]
accuracy:
 0.9333333333333333
