In [ ]:
# Trong python, để định nghĩa, làm việc với array có thể dùng list nhưng chậm.
# Numpy có đối tượng ndarray nhanh hơn 50x lần. Ngoài ra còn có nhiều hàm xây dựng sẵn hỗ trợ tính toán.
# Tham khảo:
# https://www.w3schools.com/python/numpy_intro.asp
# https://www.geeksforgeeks.org/python-numpy/?ref=lbp
# https://numpy.org/doc/stable/index.html

In [1]:
import numpy as np
# Xem version của numpy
print('Numpy version: ', np.__version__)
# document của numpy
# print(np.__doc__)

Numpy version:  1.18.5


In [72]:
print('Ma trận 0 chiều: ', np.array(1))
print('Ma trận 1 chiều: ', np.array([1, 2, 3]))
print('Ma trận 2 chiều: ', *np.array([[1, 2, 3], [4, 5, 6]]))
# Nếu có giá trị là str thì toàn bộ array là str
print('Ma trận 2 chiều: ', *np.array([[1, '2', 3], [4, 5, 6]]))

Ma trận 0 chiều:  1
Ma trận 1 chiều:  [1 2 3]
Ma trận 2 chiều:  [1 2 3] [4 5 6]
Ma trận 2 chiều:  ['1' '2' '3'] ['4' '5' '6']


In [73]:
arr3 = np.array([
                 [(1, 2, 3), [4, 5, 6]],
                 ([-1, -2, -3], [-4, -5, -6])
                ])
print('ndim: lấy số chiều của ma trận')
print('Ma trận {} chiều:\n'.format(arr3.ndim), arr3, '\n')
print('shape: lấy kích thước của ma trận')
print(arr3.shape, '\n')
print('reshape: chuyển kích thước của ma trận, phải đảm bảo shape mới phù hợp số phần tử')
print(arr3.reshape(4, 3))
print('flatten hoặc ravel: Chuyển về ma trận 1 chiều, flatten copy thành array mới, còn ravel chuyển trực tiếp')
print(arr3.flatten())
print(arr3.ravel())
print('Số phần tử của ma trận: ', arr3.size, '\n')
print('Kiểu dữ liệu của từng phần tử trong ma trận: ', arr3.dtype)

print('arr3 có tham số là list:[] và tupe:(). np.array sẽ chuyển hết về ndarray')
print(type(arr3[0]))
print(type(arr3[0][0]))
print(type(arr3[0][0][0]))


ndim: lấy số chiều của ma trận
Ma trận 3 chiều:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]] 

shape: lấy kích thước của ma trận
(2, 2, 3) 

reshape: chuyển kích thước của ma trận, phải đảm bảo shape mới phù hợp số phần tử
[[ 1  2  3]
 [ 4  5  6]
 [-1 -2 -3]
 [-4 -5 -6]]
flatten hoặc ravel: Chuyển về ma trận 1 chiều, flatten copy thành array mới, còn ravel chuyển trực tiếp
[ 1  2  3  4  5  6 -1 -2 -3 -4 -5 -6]
[ 1  2  3  4  5  6 -1 -2 -3 -4 -5 -6]
Số phần tử của ma trận:  12 

Kiểu dữ liệu của từng phần tử trong ma trận:  int32
arr3 có tham số là list:[] và tupe:(). np.array sẽ chuyển hết về ndarray
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int32'>


In [74]:
print('Thêm tham số dtype để gán kiểu cho các phần tử trong ma trận.')
arr = np.array([1, 2, 3], dtype = 'str')
print(arr)
arr = np.array(arr, dtype='int')
print(arr)

Thêm tham số dtype để gán kiểu cho các phần tử trong ma trận.
['1' '2' '3']
[1 2 3]


In [75]:
# Tạo ma trận bằng arange(start, end, step, dtype).
print(np.arange(0, 5))
print(np.arange(10, 0, -2))
print(np.arange(10, 0, -2, 'float'))

[0 1 2 3 4]
[10  8  6  4  2]
[10.  8.  6.  4.  2.]


In [91]:
# Tạo ma trận bằng linspace(start, stop, number_of_elements)
# Các phần tử cách đều nhau trong [start:stop]
print('linspace(0, 3, 5) =', np.linspace(0, 3, num=5))
print('Tham số retstep hiển thị (ma trận, bước nhảy giữa các p.tử):\n',
      np.linspace(0, 3, num=5, retstep=True), '\n')

a = np.linspace(0, 3, retstep=True)
print('Mặc định số phần tử là:', len(a[0]), '\n', a, '\n')

a = np.linspace(0, 3, 5, dtype='str')
print('Ép kiểu phần tử dtype= str: ', a, '\n')

print('Tham số endpoint mặc định = True: phần tử cuối cùng là số stop')
print(' = False phần tử cuối cùng nhỏ hơn số stop')
a = np.linspace(0, 1, 5, retstep=True)
print(a)
a = np.linspace(0, 1, 5, endpoint=False, retstep=True)
print(a)

linspace(0, 3, 5) = [0.   0.75 1.5  2.25 3.  ]
Tham số retstep hiển thị (ma trận, bước nhảy giữa các p.tử):
 (array([0.  , 0.75, 1.5 , 2.25, 3.  ]), 0.75) 

Mặc định số phần tử là: 50 
 (array([0.        , 0.06122449, 0.12244898, 0.18367347, 0.24489796,
       0.30612245, 0.36734694, 0.42857143, 0.48979592, 0.55102041,
       0.6122449 , 0.67346939, 0.73469388, 0.79591837, 0.85714286,
       0.91836735, 0.97959184, 1.04081633, 1.10204082, 1.16326531,
       1.2244898 , 1.28571429, 1.34693878, 1.40816327, 1.46938776,
       1.53061224, 1.59183673, 1.65306122, 1.71428571, 1.7755102 ,
       1.83673469, 1.89795918, 1.95918367, 2.02040816, 2.08163265,
       2.14285714, 2.20408163, 2.26530612, 2.32653061, 2.3877551 ,
       2.44897959, 2.51020408, 2.57142857, 2.63265306, 2.69387755,
       2.75510204, 2.81632653, 2.87755102, 2.93877551, 3.        ]), 0.061224489795918366) 

Ép kiểu phần tử dtype= str:  ['0.0' '0.75' '1.5' '2.25' '3.0'] 

Tham số endpoint mặc định = True: phần tử cuối cùng 

In [77]:
# eye: Tạo ma trận 2 chiều đường chéo = 1, còn lại = 0. Mặc định kiểu float
print(np.eye(2), '\n')
# k vị trí bắt đầu đường chéo, k>0 vị trí bắt đầu ở hàng thứ 0
#                              k<0 vị trí bắt đầu ở hàng cuối.
print(np.eye(4, k=2), '\n')
print(np.eye(4, k=-1), '\n')
# identity: Tạo ma trận vuông có đường chéo chính các số bằng 1.
print(np.identity(4))

[[1. 0.]
 [0. 1.]] 

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [78]:
# ones: Tạo ma trận toàn số 1.
# tham số là một số nguyên hoặc 1 tuple
print(np.ones( (3,4,5) ) , '\n')
print(np.ones(3))

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] 

[1. 1. 1.]


In [79]:
# zeros: Tạo ma trận toàn số 0.
# tham số là một số nguyên hoặc 1 tuple
print(np.zeros( (3,4) ) , '\n')
print(np.zeros(3))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[0. 0. 0.]


In [80]:
# empty: Tạo ma trận với shape cho trước, không tạo thêm giá trị mới trên bộ nhớ, dùng 1 vùng giá trị có trên bộ nhớ.
print(np.empty([3,4]), '\n')
# full: Tạo ma trận với shape, điền các giá trị cho trước, có thể là 1 số hoặc các số (bắt buộc phải có).
print(np.full((2, 3), [1, 2, 3], dtype='complex'), '\n')
print(np.full((2, 3), 1))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1.+0.j 2.+0.j 3.+0.j]
 [1.+0.j 2.+0.j 3.+0.j]] 

[[1 1 1]
 [1 1 1]]


In [92]:
# ones_like, zeros_like, ....: Tạo ma trận theo shape của ma trận khác.
a = np.arange(6); a = a.reshape((2, 3))
print(a, '\n')
print(np.ones_like(a), '\n')
print(np.zeros_like(a), '\n')
print(np.full_like(a, [-1,-2,-3]), '\n')
print(np.empty_like(a, dtype='int'), '\n')
print(np.empty_like(a, dtype='float'), '\n')

[[0 1 2]
 [3 4 5]] 

[[1 1 1]
 [1 1 1]] 

[[0 0 0]
 [0 0 0]] 

[[-1 -2 -3]
 [-1 -2 -3]] 

[[-1 -2 -3]
 [-1 -2 -3]] 

[[ 2.   0.   4. ]
 [-0.5  6.   0. ]] 



In [109]:
a = np.array([1,0,1,0])
b = np.array([1,1,0,0])
print('a=', a)
print('b=', b)
print('phép and từng cặp phần tử trong a, b')
print(np.bitwise_and(a, b), '\n')
print('phép or từng cặp phần tử trong a, b')
print(np.bitwise_or(a, b), '\n')
a = np.arange(0, 20, 4)
b = np.arange(1, 10, 2)
print('a=', a)
print('b=', b)
print('Cộng, trừ, nhân, chia theo cặp phần tử')
print('Cộng :', np.add(a,b))
print('Trừ : ', np.subtract(a,b))
print('Nhân: ', np.multiply(a,b))
print('Chia:', np.divide(a,b)) # 1/0 = infinite 0/0 = nan
print('Chia làm tròn xuống: ', np.floor_divide(a,b))
print('Chia lấy 2 ma trận nguyên, dư:, ', np.divmod(a,b))
print('Chuyển các phần tử thành số âm', np.negative(a))# positive cho số dương

a= [1 0 1 0]
b= [1 1 0 0]
phép and từng cặp phần tử trong a, b
[1 0 0 0] 

phép or từng cặp phần tử trong a, b
[1 1 1 0] 

a= [ 0  4  8 12 16]
b= [1 3 5 7 9]
Cộng, trừ, nhân, chia theo cặp phần tử
Cộng : [ 1  7 13 19 25]
Trừ :  [-1  1  3  5  7]
Nhân:  [  0  12  40  84 144]
Chia: [0.         1.33333333 1.6        1.71428571 1.77777778]
Chia làm tròn xuống:  [0 1 1 1 1]
Chia lấy 2 ma trận nguyên, dư:,  (array([0, 1, 1, 1, 1], dtype=int32), array([0, 1, 3, 5, 7], dtype=int32))
Chuyển các phần tử thành số âm [  0  -4  -8 -12 -16]


In [112]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print(arr)
print('Tạo ma trận mới, lấy phần tử theo index từ ma trận cho trước, ví dụ dòng 0 các vị trí 0, 2, 3')
print(arr[0][np.array([0, 2, 3])], '\n')
print('Lấy ma trận con 2 dòng, mỗi dòng lấy cột từ 1->3.')
print(arr[:2, 1:4], '\n')
print('Lấy phần tử theo index dòng, ứng cột, ví dụ ở đây lấy các phần tử (0, 3), (1, 2), (2, 1), (3, 0).')
print(arr[[0, 1, 2, 3], [3, 2, 1, 0]], '\n')
print('Lấy phần tử âm')
print(arr[arr < 0], '\n')
print('Thay phần tử âm = -99')
arr[arr < 0] = -99
print(arr, '\n')
# Tính element-wise (thực hiện phép tính với từng giá trị trong array)
print('Ví dụ cộng mỗi phần tử với 1. Tương tự các phép toán khác.')
print(arr + 1, '\n')
print('Lũy thừa 2 cho mỗi phần tử.')
print(arr**(2), '\n')
print('Chuyển vị ma trận.')
print(arr.T, '\n')
print('max = {}, min = {}'.format(arr.max(), arr.min()))
print('Tổng các dòng: {}'.format(sum(arr)))
print('Cộng tích lũy trên dưới trái phải (cumulative sum): \n{}'.format(arr.cumsum()))
print('Cộng tích lũy theo dòng trái phải, ghi kết quả thành cột: \n{}'.format(arr.cumsum(axis = 0)))
print('Cộng tích lũy theo cột trên dưới, ghi kết quả thành dòng: \n{}'.format(arr.cumsum(axis = 1)))
print(f'Cộng các phần tử: {arr.sum():f}')
# Căn bậc ba cbrt
print('Căn bậc 3 cbrt: ', np.cbrt(np.array([1, 8, 27, 64])))

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Tạo ma trận mới, lấy phần tử theo index từ ma trận cho trước, ví dụ dòng 0 các vị trí 0, 2, 3
[-1.  0.  4.] 

Lấy ma trận con 2 dòng, mỗi dòng lấy cột từ 1->3.
[[ 2.   0.   4. ]
 [-0.5  6.   0. ]] 

Lấy phần tử theo index dòng, ứng cột, ví dụ ở đây lấy các phần tử (0, 3), (1, 2), (2, 1), (3, 0).
[4. 6. 0. 3.] 

Lấy phần tử âm
[-1.  -0.5 -7. ] 

Thay phần tử âm = -99
[[-99.    2.    0.    4. ]
 [  4.  -99.    6.    0. ]
 [  2.6   0.    7.    8. ]
 [  3.  -99.    4.    2. ]] 

Ví dụ cộng mỗi phần tử với 1. Tương tự các phép toán khác.
[[-98.    3.    1.    5. ]
 [  5.  -98.    7.    1. ]
 [  3.6   1.    8.    9. ]
 [  4.  -98.    5.    3. ]] 

Lũy thừa 2 cho mỗi phần tử.
[[9.801e+03 4.000e+00 0.000e+00 1.600e+01]
 [1.600e+01 9.801e+03 3.600e+01 0.000e+00]
 [6.760e+00 0.000e+00 4.900e+01 6.400e+01]
 [9.000e+00 9.801e+03 1.600e+01 4.000e+00]] 

Chuyển vị ma trận.
[[-99.    4.    2.6   3. ]
 [  2.  

In [84]:
a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])
print ("Cộng ma trận:\n", a + b)
print ("Nhân ma trận theo cặp phần tử:\n", a*b)
print ("Nhân ma trận:\n", a.dot(b))

Cộng ma trận:
 [[5 5]
 [5 5]]
Nhân ma trận theo cặp phần tử:
 [[4 6]
 [6 4]]
Nhân ma trận:
 [[ 8  5]
 [20 13]]


In [17]:
a = np.arange(10).reshape(2,-1) # -1: tự chia kích thước còn lại của ma trận
b = np.repeat(1, 10).reshape(2,-1)
print('a=', a)
print('b=', b)
print('Ghép b vào a theo chiều dọc (thêm dòng vào a)')
print(np.concatenate([a, b], axis = 0))
#np.vstack([a, b]) # Cách 2
#np.r_[a, b] # Cách 3
print('Ghép b vào a theo chiều ngang (thêm phần tử vào các dòng của a)')
print(np.hstack([a, b]))
# np.concatenate([a, b], axis = 1)
#np.c_[a, b]
print('Lấy ma trận giao của a và b')
print(np.intersect1d(a, b))
print('Lấy ma trận hiệu của a - b')
print(np.setdiff1d(a, b))

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
Ghép b vào a theo chiều dọc (thêm dòng vào a)
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Ghép b vào a theo chiều ngang (thêm phần tử vào các dòng của a)
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
Lấy ma trận giao của a và b
[1]
Lấy ma trận hiệu của a - b
[0 2 3 4 5 6 7 8 9]
Vị trí các phần tử trùng nhau của a và b
(array([1], dtype=int64),)


In [33]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print('a=',a)
print('b=',b)
print('Vị trí các phần tử trùng nhau của a và b')
print(np.where(a == b)[0])
print('Lấy phần tử trong a thuộc đoạn [4;6]')
index = np.where((a >= 4) & (a <= 6))
print(a[index])
# print(a[(a>=4) & (a<=6)]) # Cách khác
a = a.reshape([-1, 2])
print('a=\n', a)
print('Đổi vị trí cột trong a')
print(a[:, [1,0]])


a= [1 2 3 2 3 4 3 4 5 6]
b= [ 7  2 10  2  7  4  9  4  9  8]
Vị trí các phần tử trùng nhau của a và b
[1 3 5 7]
Lấy phần tử trong a thuộc đoạn [4;6]
[4 4 5 6]
a=
 [[1 2]
 [3 2]
 [3 4]
 [3 4]
 [5 6]]
Đổi vị trí cột trong a
[[2 1]
 [2 3]
 [4 3]
 [4 3]
 [6 5]]
Đổi vị trí dòng trong a
[[5 6]
 [1 2]]


In [112]:
a = np.arange(12); a = a.reshape(3,4);
print(a)
print('nditer duyệt các phần tử trong ma trận')
for x in np.nditer(a): print(x, end=', ')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
nditer duyệt các phần tử trong ma trận
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 

In [69]:
# lượng giác
a = [0, np.pi / 2, np.pi / 3, np.pi]
print('a =', a)
print('Sin:', np.sin(a))
print('Arcsin:', np.arcsin(np.sin(a)))
print('Cos:', np.cos(a))
print('Tan:', np.tan(a))
print('Tanh:', np.tanh(a))
print('\nChuyển radian sang độ')
rad = np.arange(6)*np.pi/6 # 0=0 độ; pi/6=30 độ; pi/3=50 độ; pi/2=90 độ; 2pi/3=120 độ; 5pi/6=150 độ; pi=180 độ....
print('radian: ', rad)
radToDeg = np.degrees(rad)
print('độ: ', radToDeg)
# print(np.rad2deg(rad)) #Cách khác: rad2deg
print('Chuyển từ độ thành radian')
degToRad = np.deg2rad(radToDeg)
print(degToRad)

a = [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]
Sin: [0.00000000e+00 1.00000000e+00 8.66025404e-01 1.22464680e-16]
Arcsin: [0.00000000e+00 1.57079633e+00 1.04719755e+00 1.22464680e-16]
Cos: [ 1.000000e+00  6.123234e-17  5.000000e-01 -1.000000e+00]
Tan: [ 0.00000000e+00  1.63312394e+16  1.73205081e+00 -1.22464680e-16]
Tanh: [0.         0.91715234 0.78071444 0.99627208]

Chuyển radian sang độ
radian:  [0.         0.52359878 1.04719755 1.57079633 2.0943951  2.61799388]
độ:  [  0.  30.  60.  90. 120. 150.]
Chuyển từ độ thành radian
[0.         0.52359878 1.04719755 1.57079633 2.0943951  2.61799388]


In [86]:
# round : Làm tròn về số gần nhất, tùy chỉnh phần thập phân
a = np.array([-1.72, -1.58, -0.2, 0.2, 0.5, 1.5, 1.7, 2.0])
print('a=',a)
print('Làm tròn round: ', np.round(a, decimals=1))
# rint: làm tròn về số nguyên gần nhất
print('Làm tròn rint: ', np.rint(a))
# ceil: làm tròn lên (làm tròn về chiều dương vô cùng)
print('Làm tròn ceil:', np.ceil(a))
# floor: làm tròn xuống (làm tròn về chiều âm vô cùng)
print('Làm tròn floor:', np.floor(a))
# trunc: Làm tròn về 0
print('Làm tròn trunc:', np.trunc(a))

a= [-1.72 -1.58 -0.2   0.2   0.5   1.5   1.7   2.  ]
Làm tròn round:  [-1.7 -1.6 -0.2  0.2  0.5  1.5  1.7  2. ]
Làm tròn rint:  [-2. -2. -0.  0.  0.  2.  2.  2.]
Làm tròn ceil: [-1. -1. -0.  1.  1.  2.  2.  2.]
Làm tròn floor: [-2. -2. -1.  0.  0.  1.  1.  2.]
Làm tròn trunc: [-1. -1. -0.  0.  0.  1.  1.  2.]


In [91]:
a = np.array([2, 3, 4, 5])
print(np.expm1(a)) # e^x - 1 x thuộc a
print(np.exp2(a)) # 2^x x thuộc a
print(np.log10(a)) #log10(x) x thuộc a
print(np.log2(a)) #log2(x) x thuộc a
print(np.log1p(a)) #log(1 + x) x thuộc a

[  6.3890561   19.08553692  53.59815003 147.4131591 ]
[ 4.  8. 16. 32.]
[0.30103    0.47712125 0.60205999 0.69897   ]
[1.         1.5849625  2.         2.32192809]
[1.09861229 1.38629436 1.60943791 1.79175947]
