In [47]:
import numpy as np
import pandas as pd
df = pd.read_csv("Data/adult.data")
print(df.shape)
print(df.columns)
# print(df.head(5))

(32560, 15)
Index(['39', ' State-gov', ' 77516', ' Bachelors', ' 13', ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', ' 2174', ' 0',
       ' 40', ' United-States', ' <=50K'],
      dtype='object')


In [48]:
print(len(df))
df = df.sample(n=200)
print(len(df))

32560
200


In [49]:
a = df.values
print(a.shape)
y = a[:,-1:]
y = y.ravel()
print(y.shape)
print(y[:3])

(200, 15)
(200,)
[' <=50K' ' <=50K' ' <=50K']


In [50]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
y = LE.fit_transform(y)
print(y[:10])
print(len(y))
y1 = y[y==1]
print(len(y1))
y0 = y[y==0]
print(len(y0))

[0 0 0 0 0 0 0 0 0 0]
200
51
149


In [41]:
b = df.select_dtypes(include=['float64', 'int64'])
print("b's shape:", b.shape)
print(b)
X = b.values
print("X's shape:", X.shape)
print(X[:3])

b's shape: (200, 6)
       39   77516   13   2174     0   40
30078  36   33394   13      0  1887   35
18780  47  148576   15      0     0   35
23718  44  173682   10      0     0   40
12812  19  125591    7      0     0   40
30283  66  132055    9      0  1825   40
...    ..     ...  ...    ...   ...  ...
24083  60  120163   13      0     0   40
12318  29  203697   13      0     0   75
906    24  202570   13      0     0   15
9362   38  197077    9      0     0   40
19929  66  169435    9      0     0   16

[200 rows x 6 columns]
X's shape: (200, 6)
[[    36  33394     13      0   1887     35]
 [    47 148576     15      0      0     35]
 [    44 173682     10      0      0     40]]


In [51]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)
print(X)

[[0.32758621 0.02592557 0.78571429 0.         0.74087161 0.375     ]
 [0.51724138 0.24745072 0.92857143 0.         0.         0.375     ]
 [0.46551724 0.29573613 0.57142857 0.         0.         0.44444444]
 ...
 [0.12068966 0.35129532 0.78571429 0.         0.         0.09722222]
 [0.36206897 0.34073084 0.5        0.         0.         0.44444444]
 [0.84482759 0.28756804 0.5        0.         0.         0.11111111]]


In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 2)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)


(160, 6) (160,)
(40, 6) (40,)


In [54]:
#svm
from sklearn import svm
from sklearn import metrics
svm_classifier = svm.SVC(kernel='linear', gamma=0.01, C=100.)
svm_classifier.fit(X_train, y_train)

y_pred_svm = svm_classifier.predict(X_test)
print('y_pred_svm:\n', y_pred_svm)
print('y_true:\n', y_test)

acc_score_svm = metrics.accuracy_score(y_pred_svm, y_test)
print('accuracy:\n', acc_score_svm)


y_pred_svm:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
y_true:
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0
 0 1 0]
accuracy:
 0.8


In [55]:
#Phan loai voi KNN
from sklearn.neighbors import KNeighborsClassifier
k = 5
knn = KNeighborsClassifier(n_neighbors=k, metric='euclidean')
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
print('y_pred:\n', y_pred)
print('y_true:\n', y_test)

#Tính accuracy
acc_score = metrics.accuracy_score(y_pred, y_test)
print('accuracy:\n', acc_score)

y_pred:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0
 0 0 0]
y_true:
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0
 0 1 0]
accuracy:
 0.725


In [56]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model = model.fit(X_train, y_train)
y_pred_logistic = model.predict(X_test)
print('y_pred_logistic:\n', y_pred_logistic)
acc_score_logistic = metrics.accuracy_score(y_pred_logistic, y_test)
print('accuracy:\n', acc_score_logistic)

y_pred_logistic:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
accuracy:
 0.8
