In [3]:
import numpy as np
import pandas as pd
df = pd.read_csv("Data/breast-cancer-wisconsin.data")
print(df.shape)
print(df.columns)

(698, 11)
Index(['1000025', '5', '1', '1.1', '1.2', '2', '1.3', '3', '1.4', '1.5',
       '2.1'],
      dtype='object')


In [ ]:
# drop missing value


In [24]:
df = df.drop(df.columns[6], axis = 1)
data = df.values
X = data[:,1:-1]
print('X = \n', X[:3])
y = data[:,-1:]
print('y = \n', y[:3])
y = y.ravel()
print('y = \n', y[:10])

X = 
 [[5 4 4 5 7 2 1]
 [3 1 1 1 2 1 1]
 [6 8 8 1 3 7 1]]
y = 
 [[2]
 [2]
 [2]]
y = 
 [2 2 2 2 4 2 2 2 2 2]


In [25]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
y = LE.fit_transform(y)
print(y[:10])

[0 0 0 0 1 0 0 0 0 0]


In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 4)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(558, 7) (558,)
(140, 7) (140,)


In [27]:
#Phan loai voi KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k = 5
knn = KNeighborsClassifier(n_neighbors=k, metric='euclidean')
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
print('y_pred:\n', y_pred)
print('y_true:\n', y_test)

#Tính accuracy
acc_score = metrics.accuracy_score(y_pred, y_test)
print('accuracy:\n', acc_score)

y_pred:
 [1 0 1 0 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 1 0 0 0
 1 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 0 0
 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0
 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1]
y_true:
 [1 0 1 0 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 1 0 0 0
 1 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 0 0
 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0
 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 0 0 0 1]
accuracy:
 0.9785714285714285


In [28]:
#Ví dụ về SVM
from sklearn import svm
svm_classifier = svm.SVC(kernel='linear', gamma=0.01, C=100.)
svm_classifier.fit(X_train, y_train)

y_pred_svm = svm_classifier.predict(X_test)
print('y_pred_svm:\n', y_pred_svm)
print('y_true:\n', y_test)

acc_score_svm = metrics.accuracy_score(y_pred_svm, y_test)
print('accuracy:\n', acc_score_svm)

y_pred_svm:
 [1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 1 0 0 0
 1 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 0 0
 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0
 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1]
y_true:
 [1 0 1 0 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 1 0 0 0
 1 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 0 0
 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0
 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 0 0 0 1]
accuracy:
 0.9714285714285714


In [29]:
#Thử nghiệm với Logistic Regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model = model.fit(X_train, y_train)
y_pred_logistic = model.predict(X_test)
print('y_pred_logistic:\n', y_pred_logistic)
acc_score_logistic = metrics.accuracy_score(y_pred_logistic, y_test)
print('accuracy:\n', acc_score_logistic)

y_pred_logistic:
 [1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 1 0 0 0
 1 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 0 0
 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0
 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1]
accuracy:
 0.9714285714285714
