In [10]:
l1 = [0,1,2,3,4,5,6,7,8,9]
def bai1(l: list):
    evenList = [n for n in l if n%2 == 0]
    oddList = [n for n in l if n%2 != 0]
    print('Even list:', *evenList)
    print('Odd list:', *oddList)
bai1(l1)

Even list: 0 2 4 6 8
Odd list: 1 3 5 7 9


In [14]:
l2 = ['this is string 1', 0, 1, 2, 3, 'day la string 2']
def bai2(inputList: list):
    numberList = [item for item in inputList if isinstance(item, int)]
    strList = [item for item in inputList if isinstance(item, str)]
    print('Number: ', end='')
    print(*numberList, sep=', ')
    print('String: ', end='')
    print(*strList, sep=', ')
bai2(l2)

Number: 0, 1, 2, 3
String: this is string 1, day la string 2


In [31]:
mat1 = [[0,1,2],[3,4,5],[6,7,8]]
mat2 = [[1,1],[-2,2],[-1,-1]]

import numpy
mat1 = numpy.array(mat1); mat2 = numpy.array(mat2)
print('{}\n x\n {}\n =\n {}'.format(mat1, mat2, mat1.dot(mat2)))
# print(mat1.dot(mat2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 x
 [[ 1  1]
 [-2  2]
 [-1 -1]]
 =
 [[ -4   0]
 [-10   6]
 [-16  12]]
